# Generated by Django 4.0.5 on 2022-06-01 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 6, 1), null=True),
        ),
    ]
