# Generated by Django 4.0.5 on 2022-06-03 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 20, 39, 27, 981358, tzinfo=utc)),
        ),
    ]
