# Generated by Django 4.0.5 on 2022-06-03 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 20, 40, 3, 794202, tzinfo=utc)),
        ),
    ]
